name: svar_new
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  auto_size_text: ^3.0.0
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6
  firebase_storage: ^11.7.6
  avatar_glow: ^2.0.1
  confetti: ^0.7.0
  flutter_sound: ^8.1.6
  app_settings: ^5.1.1
  http: ^0.13.6
  country_code_picker: ^3.0.0
  carousel_slider: ^4.2.1
  audioplayers: ^6.0.0
  path_provider: ^2.0.11
  firebase_analytics: ^10.10.7
  just_audio: ^0.9.38
  video_player: ^2.8.7
  permission_handler: ^11.3.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/svg/
    - assets/audio/

  fonts: 
    - family: Nunito
      fonts: 
        - asset: assets/fonts/NunitoSemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NunitoBlack.ttf
          weight: 900
        - asset: assets/fonts/NunitoBold.ttf
          weight: 700
    - family: Jokerman
      fonts: 
        - asset: assets/fonts/JokermanRegular.ttf
          weight: 400
