name: svar_new
description: A new Flutter project.
version: 1.0.1+1
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  app_settings: ^5.1.1
  audioplayers: ^6.0.0 
  auto_size_text: ^3.0.0
  avatar_glow: ^2.0.1
  cached_network_image: ^3.3.0
  chewie: ^1.8.0
  cloud_firestore: ^5.4.4
  confetti: ^0.8.0
  connectivity_plus: ^6.0.5
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  flutter_sound: ^9.16.3
  flutter_svg_provider: ^1.0.0
  flutter_svg: ^2.0.9
  googleapis_auth: ^1.0.0
  googleapis: ^13.2.0
  http: ^1.2.2
  country_code_picker: ^3.0.0
  carousel_slider_plus: ^7.0.1
  carousel_slider: ^5.0.0
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  provider: ^6.1.1
  rive: ^0.13.12
  just_audio: ^0.9.18
  shared_preferences: ^2.2.2
  video_player: ^2.8.3
  camera: ^0.11.0+2
  flutter_audio_waveforms: ^1.2.1+8
  flutter_cache_manager: ^3.3.1
  page_transition: ^2.1.0
  chiclet: ^1.2.0
  intl: ^0.19.0
  flutter_tts: ^4.2.1
  vad: ^0.0.4
   
  
  
dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/svg/
    - assets/audio/
    - assets/audio/bgm/
    - assets/video/
    - assets/rive/
    # - assets/phonemes/

  fonts: 
    - family: Nunito
      fonts: 
        - asset: assets/fonts/NunitoSemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NunitoBlack.ttf
          weight: 900
        - asset: assets/fonts/NunitoBold.ttf
          weight: 700
    - family: Jokerman
      fonts: 
        - asset: assets/fonts/JokermanRegular.ttf
          weight: 400
